// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA93AZQoRXfRWdKqtlIkTL0m33fP9lOsEc',
    appId: '1:529341360402:web:384327179747ee40666bcb',
    messagingSenderId: '529341360402',
    projectId: 'smartdetection-27a0d',
    authDomain: 'smartdetection-27a0d.firebaseapp.com',
    storageBucket: 'smartdetection-27a0d.appspot.com',
    measurementId: 'G-G648BW1JCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANirWBtOi3xjk4gzXx4wb0qPBRW-epiiM',
    appId: '1:529341360402:android:42a59d36d049e3bc666bcb',
    messagingSenderId: '529341360402',
    projectId: 'smartdetection-27a0d',
    storageBucket: 'smartdetection-27a0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWrKaKGRWMBcsoz2eTnAENXZNkxb_lShY',
    appId: '1:529341360402:ios:059018d95e8837a2666bcb',
    messagingSenderId: '529341360402',
    projectId: 'smartdetection-27a0d',
    storageBucket: 'smartdetection-27a0d.appspot.com',
    iosBundleId: 'com.example.smartDetectionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWrKaKGRWMBcsoz2eTnAENXZNkxb_lShY',
    appId: '1:529341360402:ios:059018d95e8837a2666bcb',
    messagingSenderId: '529341360402',
    projectId: 'smartdetection-27a0d',
    storageBucket: 'smartdetection-27a0d.appspot.com',
    iosBundleId: 'com.example.smartDetectionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA93AZQoRXfRWdKqtlIkTL0m33fP9lOsEc',
    appId: '1:529341360402:web:739451eb9f826271666bcb',
    messagingSenderId: '529341360402',
    projectId: 'smartdetection-27a0d',
    authDomain: 'smartdetection-27a0d.firebaseapp.com',
    storageBucket: 'smartdetection-27a0d.appspot.com',
    measurementId: 'G-F4H5LV5NZ1',
  );
}
